"""Bake local ``.env`` values into a gitignored module for release builds.

    python -m ragdesk.buildenv      # ./.env -> src/ragdesk/_build_env.py
    uv build                        # the wheel now carries the values

The generated module is gitignored — the repository never contains
credentials, while distributed artifacts (PyPI wheel, bundled sidecars) can
still offer one-click connects. Only non-confidential values belong in a
public build (see SECURITY.md): GitHub client ID, Google Desktop client
credentials. The Atlassian 3LO secret is a real credential and is refused
here.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from ragdesk.envfile import parse_env_file

ENV_TO_CONST = {
    "RAGDESK_GITHUB_CLIENT_ID": "GITHUB_CLIENT_ID",
    "RAGDESK_ATLASSIAN_CLIENT_ID": "ATLASSIAN_CLIENT_ID",
    "RAGDESK_ATLASSIAN_CLIENT_SECRET": "ATLASSIAN_CLIENT_SECRET",
    "GDRIVE_CLIENT_ID": "GOOGLE_CLIENT_ID",
    "GDRIVE_CLIENT_SECRET": "GOOGLE_CLIENT_SECRET",
}
CONST_ORDER = (
    "GITHUB_CLIENT_ID",
    "ATLASSIAN_CLIENT_ID",
    "ATLASSIAN_CLIENT_SECRET",
    "GOOGLE_CLIENT_ID",
    "GOOGLE_CLIENT_SECRET",
)
REFUSED = {"ATLASSIAN_CLIENT_SECRET"}


def render_build_env(values: dict[str, str]) -> str:
    lines = [
        '"""Generated by `python -m ragdesk.buildenv` — do not edit, do not commit."""',
        "",
    ]
    for const in CONST_ORDER:
        lines.append(f"{const} = {values.get(const, '')!r}")
    lines.append("")
    return "\n".join(lines)


def write_build_env(env_path: Path, out_path: Path) -> dict[str, str]:
    """Map ``.env`` values to constants; refuses confidential values."""
    raw = parse_env_file(env_path.read_text()) if env_path.is_file() else {}
    mapped = {const: raw.get(env_name, "") for env_name, const in ENV_TO_CONST.items()}
    for const in REFUSED:
        if mapped.get(const):
            mapped[const] = ""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_build_env(mapped))
    return mapped


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m ragdesk.buildenv",
        description="Bake .env values into src/ragdesk/_build_env.py for release builds.",
    )
    parser.add_argument("--env", type=Path, default=Path(".env"))
    parser.add_argument("--out", type=Path, default=Path("src/ragdesk/_build_env.py"))
    args = parser.parse_args(argv)

    if not args.env.is_file():
        print(f"no {args.env} found — nothing baked (fine for a repo-only build)")
        return 0
    mapped = write_build_env(args.env, args.out)
    baked = [const for const, value in mapped.items() if value]
    refused = [const for const in REFUSED if parse_env_file(args.env.read_text()).get(
        next(env for env, name in ENV_TO_CONST.items() if name == const), ""
    )]
    print(f"baked {args.out} from {args.env}: {', '.join(sorted(baked)) or 'no values'}")
    if refused:
        print(
            f"refused to bake confidential values: {', '.join(sorted(refused))} "
            "(Atlassian 3LO secret belongs to the user, see SECURITY.md)"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
