"""Bake local ``.env`` values into a gitignored module for release builds.

    python -m ragdesk.buildenv      # ./.env -> src/ragdesk/_build_env.py
    uv build                        # the wheel now carries the values

The generated module is gitignored — the repository never contains
credentials, while distributed artifacts (PyPI wheel, bundled sidecars) can
still offer one-click connects. Only non-confidential values belong in a
public build (see SECURITY.md): GitHub client ID, Google Desktop client
credentials. The Atlassian 3LO secret is a real credential and is refused
here.
"""

from __future__ import annotations

import argparse
import os
from collections.abc import Mapping
from pathlib import Path

from ragdesk.envfile import parse_env_file

ENV_TO_CONST = {
    "RAGDESK_GITHUB_CLIENT_ID": "GITHUB_CLIENT_ID",
    "RAGDESK_ATLASSIAN_CLIENT_ID": "ATLASSIAN_CLIENT_ID",
    "RAGDESK_ATLASSIAN_CLIENT_SECRET": "ATLASSIAN_CLIENT_SECRET",
    "GDRIVE_CLIENT_ID": "GOOGLE_CLIENT_ID",
    "GDRIVE_CLIENT_SECRET": "GOOGLE_CLIENT_SECRET",
    "RAGDESK_MS_CLIENT_ID": "MS_CLIENT_ID",
}
CONST_ORDER = (
    "GITHUB_CLIENT_ID",
    "ATLASSIAN_CLIENT_ID",
    "ATLASSIAN_CLIENT_SECRET",
    "GOOGLE_CLIENT_ID",
    "GOOGLE_CLIENT_SECRET",
    "MS_CLIENT_ID",
)
REFUSED = {"ATLASSIAN_CLIENT_SECRET"}


def render_build_env(values: dict[str, str]) -> str:
    lines = [
        '"""Generated by `python -m ragdesk.buildenv` — do not edit, do not commit."""',
        "",
    ]
    for const in CONST_ORDER:
        lines.append(f"{const} = {values.get(const, '')!r}")
    lines.append("")
    return "\n".join(lines)


def write_build_env(
    env_path: Path, out_path: Path, environ: Mapping[str, str] | None = None
) -> dict[str, str]:
    """Map ``.env`` values (then environment variables) to constants.

    The environment fallback is for CI: release workflows export the client IDs
    from repository secrets and get the same wheel a local ``.env`` build makes.
    Confidential values are refused either way.
    """
    raw = parse_env_file(env_path.read_text()) if env_path.is_file() else {}
    environment = os.environ if environ is None else environ
    for env_name in ENV_TO_CONST:
        if not raw.get(env_name) and environment.get(env_name):
            raw[env_name] = str(environment[env_name])
    mapped = {const: raw.get(env_name, "") for env_name, const in ENV_TO_CONST.items()}
    for const in REFUSED:
        if mapped.get(const):
            mapped[const] = ""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_build_env(mapped))
    return mapped


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m ragdesk.buildenv",
        description="Bake .env values into src/ragdesk/_build_env.py for release builds.",
    )
    parser.add_argument("--env", type=Path, default=Path(".env"))
    parser.add_argument("--out", type=Path, default=Path("src/ragdesk/_build_env.py"))
    args = parser.parse_args(argv)

    mapped = write_build_env(args.env, args.out)
    baked = [const for const, value in mapped.items() if value]
    source = str(args.env) if args.env.is_file() else "the environment"
    print(f"baked {args.out} from {source}: {', '.join(sorted(baked)) or 'no values'}")
    env_values = parse_env_file(args.env.read_text()) if args.env.is_file() else {}
    refused = sorted(
        const
        for env_name, const in ENV_TO_CONST.items()
        if const in REFUSED and (env_values.get(env_name) or os.environ.get(env_name))
    )
    if refused:
        print(
            f"refused to bake confidential values: {', '.join(refused)} "
            "(Atlassian 3LO secret belongs to the user, see SECURITY.md)"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
